apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-webhook
  name: auth-webhook
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-webhook
  strategy: {}
  template:
    metadata:
      labels:
        app: auth-webhook
    spec:
      containers:
        - image: aifeierwithinmkt/auth-github-webhook
          name: auth-github-webhook
          resources: {}
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: default
spec:
  selector:
    app: auth-webhook
  ports:
    - name: auth
      protocol: TCP
      port: 80
      targetPort: 3000